import {
  Headphones,
  Users,
  Megaphone,
  Target,
  BookOpen,
  ShoppingCart,
  Phone,
  Mail,
  MapPin,
  CheckCircle,
  Briefcase,
  MessageCircle,
  TrendingUp,
  Shield,
  Heart,
  Handshake,
  Calendar,
  FileText,
  Layout,
  BarChart3,
  LucideIcon,
} from "lucide-react";
import type { IconKey } from "./content";

export const iconMap: Record<IconKey, LucideIcon> = {
  headphones: Headphones,
  users: Users,
  megaphone: Megaphone,
  target: Target,
  "book-open": BookOpen,
  "shopping-cart": ShoppingCart,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  "check-circle": CheckCircle,
  briefcase: Briefcase,
  "message-circle": MessageCircle,
  "trending-up": TrendingUp,
  shield: Shield,
  heart: Heart,
  handshake: Handshake,
  calendar: Calendar,
  "file-text": FileText,
  layout: Layout,
  "bar-chart": BarChart3,
};
